export type ConstitutionSection = {
  heading: string;
  paragraphs: string[];
  bullets?: string[];
};

export const constitutionSections: ConstitutionSection[] = [
  { heading: 'A) Introduction', paragraphs: ["Kirinyaga HealthCare Workers' welfare (KHCWW) was initiated to strengthen cohesiveness, relationship, interaction and support one another among the health workers. The welfare involves all the Healthcare Workers in Kirinyaga County who are willing to join welfare. The welfare shall perform activities agreed upon by the members during the initial formation meeting and any other activity that the members shall agree on during any other meeting where two-third votes shall approve."] },
  { heading: 'B) Objectives', paragraphs: ['Main objective: To bring KHCWs together and cater for their welfare.', 'Specific objectives:'], bullets: ['To unite the KHCWs', 'To help the KHCWs in times of need', 'To encourage participation amongst the KHCWs in times of joy and sorrow', 'To bring the overall development of the KHCWs socially, economically and professionally.'] },
  { heading: 'C) Membership', paragraphs: ['Membership is open to all KHCWS and it is voluntary.'], bullets: ['A person becomes a member upon paying a registration fee of Ksh.400.', 'There shall be a registration form to capture member\'s personal information which shall be in agreement with the constitution – done online.', 'Every registered member shall be required to pay a monthly contribution of Ksh 300.', 'A new member shall be required to wait for a period of about six months before enjoying the welfare packages.', 'Every registered member shall be required to participate fully in activities organized by the welfare.'] },
  { heading: 'D) Discipline', paragraphs: [], bullets: ['Monthly contribution shall be required on or before 15th of every month, failure to which it shall attract a penalty of Ksh 50 every month.', 'Personal contribution shall be required to be up to date for any member to benefit from the welfare.', 'Failure to pay monthly contribution for 2 consecutive months will lead to the member getting a warning. In the event that such a member, one month after the warning, does not pay up, he(s) ceases to be a member of the welfare.', 'A newly employed person including officers transferred from elsewhere willing to join the welfare shall do so only in January.', 'If it is verified that a member willfully gave wrong information with intention to mislead or to defraud the welfare of any amount of money, such a member shall pay a fine equivalent to one year contribution and shall not benefit from the welfare with what may have been otherwise given to the relative as the case may be.'] },
  { heading: 'E) Office Bearers', paragraphs: [], bullets: ['Chairperson: Chairs all committees and general meetings, is a signatory to the bank account and is chief executive of the welfare.', 'Vice Chairperson: Deputizes the chairperson on all responsibilities except being signatory to the bank account.', 'Secretary: Keeps welfare records, receives and files correspondences, sends correspondences, takes meeting minutes and is a signatory to the bank account.', 'Vice Secretary: Deputizes the secretary on all responsibilities except being a signatory to the bank account.', 'Treasurer: Receives and pays all welfare money, is a signatory to the bank account, keeps current financial records and prepares the annual report for general meetings.', 'Patron: KCRH Manager. Must be a member, oversees welfare elections and links the welfare with administration and other important offices.'] },
  { heading: 'F) General Elections', paragraphs: [], bullets: ['Elections shall be held every 3 years.', 'They will be done through secret ballot.', 'Only registered active members will be allowed to participate in the elections.', 'Elections shall be held on one person one vote basis.', 'Departments shall forward representatives 3 days prior to elections.', 'Any registered member can be elected to hold any office.'] },
  { heading: 'G) By Election', paragraphs: [], bullets: ['If an official dies, resigns, transfers or ceases to be a member, a by-election shall be conducted within one month.', 'If more than half of the office bearers cease to be members, retire, transfer or resign, a general election shall be conducted within one month.'] },
  { heading: 'H) Vote of No Confidence', paragraphs: [], bullets: ['A vote of no confidence can be passed on any office bearer.', 'A vote of no confidence shall require the support of more than two thirds (2/3) of the committee members.', 'If a vote of no confidence is passed on more than half (1/2) of the office bearers a general election shall be conducted within one month.'] },
  { heading: 'I) Finances', paragraphs: ['Sources:'], bullets: ['Members contribution', 'Projects', 'Well-wishers and friends', 'Banking: All moneys shall be banked at Cooperative Bank Kerugoya branch through Lipa na M-pesa. Pay bill No. 400200 then Account No. 40088588, or direct deposit at Co-operative Bank through A/C No. 01134568843700.', 'The signatories shall be the Chairman, Secretary and the Treasurer.', 'Withdrawals shall be made by all the three signatories.'] },
  { heading: 'J) Activities / Expenditure', paragraphs: ['Joyous moments: In case of a wedding, the welfare shall contribute:'], bullets: ['One principal member – Ksh.25,000', 'Two principal members – Ksh.50,000'] },
  { heading: 'K) Somber Moments', paragraphs: ['To support members in case of death of nuclear family and the four (4) parents:'], bullets: ['Principal members – Ksh.50,000', 'Nuclear family: Spouse – Ksh.40,000; Child – Ksh.30,000', 'Parent – Ksh.20,000', 'Members shall have representation for burial with at least 5 members. If possible, every department ought to be represented.', 'In case of an occurrence where two principal members are involved, each member shall benefit equally as per the constitution.'] },
  { heading: 'L) End of Year', paragraphs: ['There shall be an end of year AGM and teambuilding party in December each year. The remaining funds shall be appropriated in investment as per the AGM 2025 11th December Financial Statement and Investment report.'] },
  { heading: 'M) Retirement', paragraphs: [], bullets: ['During the AGM the retirees will be appreciated with a farewell gift of Ksh. 20,000.', 'The retiree shall notify the welfare executive through the secretary by January each year.', 'Any member, after retirement, willing to continue being a member of the welfare shall be allowed to do so and therefore continue with the monthly contributions.', 'Such a member shall be eligible for all other benefits provided for by the welfare except for retirement.'] },
  { heading: 'N) Meetings', paragraphs: ['General meetings:'], bullets: ['AGM: Shall be held annually. One (1) month notice shall be given. Financial report shall be required during meetings. A quorum of half (1/2) of the members shall be required.', 'Ordinary meetings: Ordinary meetings shall be held anytime as need may arise.'] },
  { heading: 'O) Amendments', paragraphs: ['Any clause in the constitution can be amended by not less than 2/3 of the members. In case of a clause being repealed more than 2/3 of the members shall be required to support.'] },
  { heading: 'P) Dissolution', paragraphs: ['Members can call for dissolution of the welfare. Dissolution shall require the support of 2/3 or more members. Upon dissolution the assets shall be divided amongst the registered members or dealt with in any other way the members shall deem appropriate.'] },
];
